/**
 ******************************************************************************
 * @file    ext_flash_test.c
 * @brief   External flash (MX25LM51245G) communication verification test.
 *
 * HOW IT WORKS
 * ============
 * After MX_OCTOSPI1_Init(), the flash is sitting in OPI (8-8-8) mode and
 * is memory-mapped at 0x90000000.  To send command-level transactions we
 * must first call HAL_OSPI_Abort() to leave memory-mapped mode, then
 * re-enable it when we are done.  This module wraps that pattern cleanly
 * so nothing else in the project needs to care about it.
 *
 * TEST SEQUENCE
 * =============
 *  1. Exit memory-mapped mode
 *  2. Read JEDEC ID → expect C2 85 3A (Macronix MX25LM51245G)
 *  3. Erase the first 4 KB subsector  (address 0x000000)
 *  4. Write one 256-byte page with a known pattern  (0xA5 ^ byte_index)
 *  5. Re-enable memory-mapped mode
 *  6. Read the 256 bytes back via the mapped pointer and compare
 *
 * All results are printed over UART1 at whatever baud rate CubeMX has
 * configured (typically 115200).
 ******************************************************************************
 */

#include "ext_flash_test.h"

#include "octospi.h"          /* hospi1                                       */
#include "mx25lm51245g.h"     /* MX25LM51245G_* driver functions              */
#include "usart.h"            /* huart1                                       */

#include <stdarg.h>
#include <stdio.h>
#include <string.h>

/* -------------------------------------------------------------------------
 * Configuration
 * -------------------------------------------------------------------------*/

/** Base address where OSPI1 is memory-mapped by the STM32U5 OCTOSPI manager */
#define FLASH_MAPPED_BASE       (0x90000000UL)

/** Flash address of the subsector we will erase/write during the test.
 *  Using the very first 4 KB block.  Change this if sector 0 holds
 *  pre-programmed data you want to preserve. */
#define TEST_ADDR               (0x00000000UL)

/** LVGL / NeoChrome reads images from mapped memory during render.
 *  We only run the test before the scheduler starts, so there is no
 *  concurrent access to worry about.  Add a mutex here if you ever
 *  call this at run-time while LVGL is active. */

/* -------------------------------------------------------------------------
 * Internal helpers
 * -------------------------------------------------------------------------*/

/** Forward-declared in octospi.c (non-static linkage) */
extern int32_t OSPI_NOR_EnableMemoryMappedMode(OSPI_HandleTypeDef *hospi);

/** OSPI handle generated by CubeMX */
extern OSPI_HandleTypeDef hospi1;

/* -------------------------------------------------------------------------- */

static void _uart_print(const char *msg)
{
    HAL_UART_Transmit(&huart2, (uint8_t *)msg, (uint16_t)strlen(msg), 1000U);
}

static void _uart_printf(const char *fmt, ...)
{
    char buf[160];
    va_list args;
    va_start(args, fmt);
    vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);
    _uart_print(buf);
}

/* --------------------------------------------------------------------------
 * Exit / enter memory-mapped mode
 * --------------------------------------------------------------------------*/

/**
 * @brief  Abort the current OSPI transaction (exits memory-mapped mode).
 *         After this call, command-level API functions (WriteEnable, Erase…)
 *         can be used normally.
 */
static int32_t _exit_mapped_mode(void)
{
    if (HAL_OSPI_Abort(&hospi1) != HAL_OK)
    {
        return -1;
    }
    HAL_Delay(1U); /* brief settle time */
    return 0;
}

/**
 * @brief  Re-enable OPI STR memory-mapped mode.
 *         After this call the flash content is directly readable at
 *         FLASH_MAPPED_BASE; command-level calls will no longer work.
 */
static int32_t _enter_mapped_mode(void)
{
    return OSPI_NOR_EnableMemoryMappedMode(&hospi1);
}

/* =========================================================================
 * Public function
 * =========================================================================*/

FlashTestResult_t ext_flash_run_test(void)
{
    uint8_t  jedec_id[3];
    uint8_t  write_buf[256];
    uint32_t i;
    uint32_t errors;
    FlashTestResult_t result = FLASH_TEST_OK;

    _uart_print("\r\n");
    _uart_print("╔══════════════════════════════════════╗\r\n");
    _uart_print("║     EXT FLASH (MX25LM51245G) TEST    ║\r\n");
    _uart_print("╚══════════════════════════════════════╝\r\n");

    /* ------------------------------------------------------------------
     * STEP 1 — Exit memory-mapped mode
     * ------------------------------------------------------------------ */
    _uart_print("[1/5] Exiting memory-mapped mode ... ");

    if (_exit_mapped_mode() != 0)
    {
        _uart_print("FAIL\r\n  HAL_OSPI_Abort returned error.\r\n");
        /* Can't continue without command access */
        return FLASH_TEST_JEDEC_FAIL;
    }
    _uart_print("OK\r\n");

    /* ------------------------------------------------------------------
     * STEP 2 — Read JEDEC ID
     *
     *  Macronix MX25LM51245G:
     *    Manufacturer ID  : 0xC2
     *    Memory Type      : 0x85  (3V, MX25LM series)
     *    Memory Density   : 0x3A  (512 Mb)
     * ------------------------------------------------------------------ */
    _uart_print("[2/5] Reading JEDEC ID ... ");

    if (MX25LM51245G_ReadID(&hospi1,
                             MX25LM51245G_OPI_MODE,
                             MX25LM51245G_STR_TRANSFER,
                             jedec_id) != MX25LM51245G_OK)
    {
        _uart_print("FAIL\r\n  ReadID command failed.\r\n");
        _enter_mapped_mode(); /* always restore */
        return FLASH_TEST_JEDEC_FAIL;
    }

    _uart_printf("OK\r\n  ID bytes: %02X %02X %02X\r\n",
                 jedec_id[0], jedec_id[1], jedec_id[2]);

    if (jedec_id[0] != 0xC2U || jedec_id[1] != 0x85U || jedec_id[2] != 0x3AU)
    {
        _uart_print("  WARNING: Unexpected ID (expected C2 85 3A).\r\n"
                    "  Continuing — the driver may have different expectations.\r\n");
        /* Treat as non-fatal; the erase/write test is the real proof. */
    }
    else
    {
        _uart_print("  Manufacturer confirmed: Macronix MX25LM51245G\r\n");
    }

    /* ------------------------------------------------------------------
     * STEP 3 — Erase first 4 KB subsector
     * ------------------------------------------------------------------ */
    _uart_printf("[3/5] Erasing 4KB subsector @ 0x%08lX ... ", TEST_ADDR);

    if (MX25LM51245G_WriteEnable(&hospi1,
                                  MX25LM51245G_OPI_MODE,
                                  MX25LM51245G_STR_TRANSFER) != MX25LM51245G_OK)
    {
        _uart_print("FAIL\r\n  WriteEnable (before erase) failed.\r\n");
        _enter_mapped_mode();
        return FLASH_TEST_ERASE_FAIL;
    }

    if (MX25LM51245G_BlockErase(&hospi1,
                                 MX25LM51245G_OPI_MODE,
                                 MX25LM51245G_STR_TRANSFER,
                                 MX25LM51245G_4BYTES_SIZE,
                                 TEST_ADDR,
                                 MX25LM51245G_ERASE_4K) != MX25LM51245G_OK)
    {
        _uart_print("FAIL\r\n  BlockErase command failed.\r\n");
        _enter_mapped_mode();
        return FLASH_TEST_ERASE_FAIL;
    }

    /* Poll WIP (Write In Progress) bit until the erase finishes */
    if (MX25LM51245G_AutoPollingMemReady(&hospi1,
                                          MX25LM51245G_OPI_MODE,
                                          MX25LM51245G_STR_TRANSFER) != MX25LM51245G_OK)
    {
        _uart_print("FAIL\r\n  Timeout waiting for erase to complete.\r\n");
        _enter_mapped_mode();
        return FLASH_TEST_ERASE_FAIL;
    }
    _uart_print("OK\r\n");

    /* ------------------------------------------------------------------
     * STEP 4 — Write one page (256 bytes) with a known pattern
     *
     *  Pattern: write_buf[i] = 0xA5 ^ i
     *  Easy to verify by eye on a logic analyser or memory dump.
     * ------------------------------------------------------------------ */
    _uart_printf("[4/5] Programming 256 bytes @ 0x%08lX ... ", TEST_ADDR);

    for (i = 0U; i < 256U; i++)
    {
        write_buf[i] = (uint8_t)(0xA5U ^ i);
    }

    if (MX25LM51245G_WriteEnable(&hospi1,
                                  MX25LM51245G_OPI_MODE,
                                  MX25LM51245G_STR_TRANSFER) != MX25LM51245G_OK)
    {
        _uart_print("FAIL\r\n  WriteEnable (before program) failed.\r\n");
        _enter_mapped_mode();
        return FLASH_TEST_WRITE_FAIL;
    }

    if (MX25LM51245G_PageProgram(&hospi1,
                                  MX25LM51245G_OPI_MODE,
                                  MX25LM51245G_4BYTES_SIZE,
                                  write_buf,
                                  TEST_ADDR,
                                  256U) != MX25LM51245G_OK)
    {
        _uart_print("FAIL\r\n  PageProgram command failed.\r\n");
        _enter_mapped_mode();
        return FLASH_TEST_WRITE_FAIL;
    }

    if (MX25LM51245G_AutoPollingMemReady(&hospi1,
                                          MX25LM51245G_OPI_MODE,
                                          MX25LM51245G_STR_TRANSFER) != MX25LM51245G_OK)
    {
        _uart_print("FAIL\r\n  Timeout waiting for program to complete.\r\n");
        _enter_mapped_mode();
        return FLASH_TEST_WRITE_FAIL;
    }
    _uart_print("OK\r\n");

    /* ------------------------------------------------------------------
     * STEP 5 — Re-enable memory-mapped mode and verify via pointer
     *
     *  Reading through the mapped address is the exact same path that
     *  LVGL / NeoChrome will use, so this confirms end-to-end.
     * ------------------------------------------------------------------ */
    _uart_print("[5/5] Restoring memory-mapped mode and verifying ... ");

    if (_enter_mapped_mode() != 0)
    {
        _uart_print("FAIL\r\n  Could not re-enter memory-mapped mode.\r\n");
        /* Flash state unknown — do not attempt more operations */
        return FLASH_TEST_VERIFY_FAIL;
    }

    /* Compare written data against the mapped flash window */
    const volatile uint8_t *mapped = (const volatile uint8_t *)FLASH_MAPPED_BASE;
    errors = 0U;

    for (i = 0U; i < 256U; i++)
    {
        uint8_t expected = (uint8_t)(0xA5U ^ i);
        uint8_t actual   = mapped[i];

        if (actual != expected)
        {
            errors++;
            if (errors <= 5U) /* show first 5 mismatches */
            {
                _uart_printf("\r\n  MISMATCH @ byte %3lu : wrote 0x%02X, read 0x%02X",
                             i, expected, actual);
            }
        }
    }

    if (errors == 0U)
    {
        _uart_print("OK\r\n");
        _uart_print("  All 256 bytes match perfectly.\r\n");
    }
    else
    {
        _uart_printf("\r\n  FAIL: %lu byte(s) mismatched.\r\n", errors);
        result = FLASH_TEST_VERIFY_FAIL;
    }

    /* ------------------------------------------------------------------
     * Summary
     * ------------------------------------------------------------------ */
    _uart_print("──────────────────────────────────────\r\n");
    if (result == FLASH_TEST_OK)
    {
        _uart_print("  RESULT: ✓ PASSED — flash is healthy.\r\n");
        _uart_print("  Next step: mount LittleFS and create the UI directory tree.\r\n");
    }
    else
    {
        _uart_printf("  RESULT: ✗ FAILED (code %d)\r\n", (int)result);
        _uart_print("  Check wiring, OSPI clock settings, and dummy cycle config.\r\n");
    }
    _uart_print("──────────────────────────────────────\r\n\r\n");

    return result;
}
